// =============================================
// Merged JS File
// This file is automatically generated by merge_js_files.py
// Do not edit this file directly. Update source files instead.
// This file merges the following JavaScript files:
// - App.js
// - App.test.js
// - components\Auth\AuthContext.js
// - components\Auth\Login.js
// - components\Auth\Logout.js
// - components\Auth\Register.js
// - components\Collection.js
// - components\CreateData.js
// - components\DeleteData.js
// - components\Header.js
// - components\Home.js
// - components\ObjectDetail.js
// - components\ProtectedRoute.js
// - components\ReadData.js
// - components\RecordManager.js
// - components\ResultsPage.js
// - components\SearchBox.js
// - components\SearchPage.js
// - components\UpdateData.js
// - components\constants.js
// - components\exportRecordsToCSV.js
// - firebase.js
// - index.js
// - reportWebVitals.js
// - setupTests.js
// - utils\fetchData.js
// =============================================



// ---------------------------------------------
// BEGIN: App.js
// ---------------------------------------------

import React from "react";
import "./App.css";
import { Routes, Route } from "react-router-dom";
import Header from "./components/Header"; // Import Header Component
import Login from "./components/Auth/Login"; // Import Login Component
import Register from "./components/Auth/Register"; // Import Register Component
import Logout from "./components/Auth/Logout"; // Import Logout Component
import ProtectedRoute from "./components/ProtectedRoute"; // Import ProtectedRoute
import Home from "./components/Home"; // Import Home Component
import RecordManager from "./components/RecordManager"; // Import RecordManager
import SearchPage from "./components/SearchPage"; // Import SearchPage Component
import Collection from "./components/Collection"; // Import Collection Component
import ObjectDetail from "./components/ObjectDetail"; // Import ObjectDetail Component
import CreatePage from "./components/CreateData"; // Import the CreatePage component
import ResultsPage from "./components/ResultsPage"; // Import ResultsPage Component

function App() {
  return (
    <div className="App">
      <Header />
      <main>
        <Routes>
          {/* Landing page */}
          <Route path="/" element={<Home />} />

          {/* Public routes */}
          <Route path="/login" element={<Login />} />
          <Route path="/register" element={<Register />} />

          {/* Search page */}
          <Route path="/search" element={<SearchPage />} />

          {/* Results page */}
          <Route path="/results" element={<ResultsPage />} />

          <Route path="/object/:objectId" element={<ObjectDetail />} />

          {/* Collection page */}
          <Route path="/collection" element={<Collection />} />

          {/* Object detail page */}
          <Route path="/object/:objectId" element={<ObjectDetail />} />

          {/* Protected routes */}
          <Route
            path="/records"
            element={
              <ProtectedRoute>
                <RecordManager />
              </ProtectedRoute>
            }
          />
          <Route
            path="/create"
            element={
              <ProtectedRoute>
                <CreatePage />
              </ProtectedRoute>
            }
          />
          <Route
            path="/logout"
            element={
              <ProtectedRoute>
                <Logout />
              </ProtectedRoute>
            }
          />
        </Routes>
      </main>
    </div>
  );
}

export default App;


// ---------------------------------------------
// END: App.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: App.test.js
// ---------------------------------------------

import { render, screen } from '@testing-library/react';
import App from './App';

test('renders learn react link', () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});


// ---------------------------------------------
// END: App.test.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Auth\AuthContext.js
// ---------------------------------------------

import React, { createContext, useContext, useEffect, useState } from "react";
import { onAuthStateChanged, getAuth } from "firebase/auth";
import { ref, get } from "firebase/database";
import { db } from "../../firebase"; // Adjust the path to your firebase.js

// Create the AuthContext
const AuthContext = createContext();

// AuthProvider component to wrap the app
export const AuthProvider = ({ children }) => {
  const [currentUser, setCurrentUser] = useState(null);
  const [emailVerified, setEmailVerified] = useState(false);
  const [userType, setUserType] = useState("regular");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const auth = getAuth();

    // Subscribe to auth state changes
    const unsubscribe = onAuthStateChanged(auth, async (user) => {
      if (user) {
        setCurrentUser(user);
        setEmailVerified(user.emailVerified);

        try {
          // Fetch the userType from the Realtime Database
          const userRef = ref(db, `users/${user.uid}/userType`);
          const snapshot = await get(userRef);

          if (snapshot.exists()) {
            setUserType(snapshot.val());
          } else {
            console.warn("No userType found for this user; defaulting to regular.");
            setUserType("regular"); // Default to 'regular' if no userType exists
          }
        } catch (error) {
          console.error("Error fetching userType:", error.message);
          setUserType("regular"); // Fallback to 'regular' on error
        }
      } else {
        // Reset states when user logs out
        setCurrentUser(null);
        setEmailVerified(false);
        setUserType("regular");
      }

      setLoading(false); // Authentication state resolved
    });

    // Cleanup the auth state listener on unmount
    return () => {
      unsubscribe();
    };
  }, []);

  const value = {
    currentUser,
    emailVerified,
    userType,
    isLoggedIn: !!currentUser, // Added isLoggedIn property
  };

  return (
    <AuthContext.Provider value={value}>
      {!loading ? children : <div>Loading...</div>}
    </AuthContext.Provider>
  );
};

// Custom hook to use AuthContext
export const useAuth = () => {
  return useContext(AuthContext);
};


// ---------------------------------------------
// END: components\Auth\AuthContext.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Auth\Login.js
// ---------------------------------------------

import React, { useState } from 'react';
import { signInWithEmailAndPassword } from 'firebase/auth';
import { useNavigate, Link } from 'react-router-dom';
import { auth } from '../../firebase';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      await signInWithEmailAndPassword(auth, email, password);
      setError('');
      navigate('/search');
    } catch (err) {
      setError('Invalid credentials. Please try again.');
    }
  };

  return (
    <div className="max-w-md mx-auto p-5 bg-white shadow-lg rounded-lg">
      <h2 className="text-2xl font-bold mb-4">Login</h2>
      <p className="text-gray-600 mb-4">
        Please login with your email and password. If you don't have an account,{' '}
        <Link to="/register" className="text-blue-500 hover:underline">
          register here
        </Link>.
      </p>
      <form onSubmit={handleLogin} className="space-y-4">
        <div>
          <label className="block text-gray-700 font-medium mb-1">Email:</label>
          <input
            type="email"
            placeholder="Enter your email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
        </div>
        <div>
          <label className="block text-gray-700 font-medium mb-1">Password:</label>
          <input
            type="password"
            placeholder="Enter your password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
        </div>
        <button
          type="submit"
          className="w-full py-2 px-4 bg-blue-500 text-white font-bold rounded hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400"
        >
          Login
        </button>
      </form>
      {error && <p className="text-red-500 mt-4">{error}</p>}
    </div>
  );
};

export default Login;


// ---------------------------------------------
// END: components\Auth\Login.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Auth\Logout.js
// ---------------------------------------------

import React, { useState } from 'react';
import { signOut } from 'firebase/auth';
import { auth } from '../../firebase';
import { useNavigate } from 'react-router-dom';

const Logout = () => {
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  const handleLogout = async () => {
    setIsLoading(true); // Start loading state
    try {
      // Perform sign-out operation
      await signOut(auth);

      // Navigate to the login page after successful logout
      navigate('/login');

      console.log('User successfully logged out.');
    } catch (error) {
      // Handle potential logout errors
      console.error('Error during logout:', error.message);
      alert('Failed to log out. Please try again.');
    } finally {
      // Always reset loading state
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
      <div className="w-full max-w-md bg-white shadow-md rounded-lg p-8">
        <h2 className="text-2xl font-bold text-center mb-6">Are you sure you want to log out?</h2>
        <p className="text-gray-600 text-center mb-6">
          Click the button below to securely log out of your account.
        </p>
        <div className="flex justify-center">
          <button
            onClick={handleLogout}
            disabled={isLoading}
            className={`flex items-center justify-center w-full bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300 ${
              isLoading ? 'opacity-50 cursor-not-allowed' : ''
            }`}
          >
            {isLoading ? (
              <svg
                className="animate-spin h-5 w-5 mr-2 text-white"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                ></circle>
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8v8z"
                ></path>
              </svg>
            ) : null}
            {isLoading ? 'Logging Out...' : 'Logout'}
          </button>
        </div>
        <p className="text-sm text-gray-500 mt-4 text-center">
          Note: You will be redirected to the login page after logging out.
        </p>
      </div>
    </div>
  );
};

export default Logout;


// ---------------------------------------------
// END: components\Auth\Logout.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Auth\Register.js
// ---------------------------------------------

import React, { useState } from 'react';
import { createUserWithEmailAndPassword, sendEmailVerification } from 'firebase/auth';
import { ref, set } from 'firebase/database';
import { auth, db } from '../../firebase';
import { useNavigate } from 'react-router-dom';

const Register = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleRegister = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const userId = userCredential.user.uid;

      await set(ref(db, `users/${userId}`), {
        email,
        userType: 'regular',
      });

      await sendEmailVerification(auth.currentUser);
      alert('Registration successful! A verification email has been sent. Please verify your email before logging in.');

      navigate('/login');
    } catch (error) {
      setError('Registration failed: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-md mx-auto p-5 bg-white shadow-lg rounded-lg">
      <h2 className="text-2xl font-bold mb-4">Register</h2>
      <p className="text-gray-600 mb-4">
        Please enter your email and password to create an account. After registering, you’ll receive a verification email. Make sure to verify your email before logging in.
      </p>
      <form onSubmit={handleRegister} className="space-y-4">
        {error && <p className="text-red-500">{error}</p>}
        <div>
          <label className="block text-gray-700 font-medium mb-1">Email:</label>
          <input
            type="email"
            placeholder="Enter your email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
        </div>
        <div>
          <label className="block text-gray-700 font-medium mb-1">Password:</label>
          <input
            type="password"
            placeholder="Enter your password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
        </div>
        <button
          type="submit"
          disabled={loading}
          className={`w-full py-2 px-4 text-white font-bold rounded focus:outline-none focus:ring-2 ${
            loading ? 'bg-gray-400 cursor-not-allowed' : 'bg-blue-500 hover:bg-blue-700 focus:ring-blue-400'
          }`}
        >
          {loading ? 'Registering...' : 'Register'}
        </button>
      </form>
    </div>
  );
};

export default Register;


// ---------------------------------------------
// END: components\Auth\Register.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Collection.js
// ---------------------------------------------

import React, { useState, useEffect, useCallback } from "react";
import { Link } from "react-router-dom";
import { getDatabase, ref, onValue } from "firebase/database";
import { objectTypes } from "./constants";

const Collection = () => {
  const [objects, setObjects] = useState([]);
  const [filteredResults, setFilteredResults] = useState([]);
  const [filters, setFilters] = useState({
    object_title: "",
    object_type: "",
    object_id: "",
    title: "",
  });

  useEffect(() => {
    const db = getDatabase();
    const objectsRef = ref(db, "objects");

    onValue(objectsRef, (snapshot) => {
      const data = snapshot.val();
      const results = Object.entries(data || {}).map(([key, value]) => ({
        object_id: key,
        ...value,
      }));
      setObjects(results);
      setFilteredResults(results);
    });
  }, []);

  const applyFilters = useCallback(() => {
    setFilteredResults(
      objects.filter((obj) => {
        const matchesObjectTitle =
          !filters.object_title ||
          obj.object_title?.toLowerCase().includes(filters.object_title.toLowerCase());
        const matchesObjectType =
          !filters.object_type || obj.object_type === filters.object_type;
        const matchesObjectId =
          !filters.object_id ||
          obj.object_id?.toLowerCase().includes(filters.object_id.toLowerCase());
        const matchesTitle =
          !filters.title ||
          obj.title?.toLowerCase().includes(filters.title.toLowerCase());
        return matchesObjectTitle && matchesObjectType && matchesObjectId && matchesTitle;
      })
    );
  }, [filters, objects]);

  const handleFilterChange = (e) => {
    const { name, value } = e.target;
    setFilters((prevFilters) => ({
      ...prevFilters,
      [name]: value,
    }));
  };

  useEffect(() => {
    applyFilters();
  }, [applyFilters]);

  return (
    <div className="flex min-h-screen">
      {/* Left Filter Panel */}
      <aside className="w-1/4 bg-gray-100 p-4 border-r border-gray-300">
        <h2 className="text-xl font-bold mb-4">Filters</h2>
        <input
          type="text"
          name="object_title"
          placeholder="Filter by Object Title"
          value={filters.object_title}
          onChange={handleFilterChange}
          className="w-full p-2 mb-4 border rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
        <select
          name="object_type"
          value={filters.object_type}
          onChange={handleFilterChange}
          className="w-full p-2 mb-4 border rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
        >
          <option value="">All Object Types</option>
          {objectTypes.map((type) => (
            <option key={type} value={type}>
              {type}
            </option>
          ))}
        </select>
        <input
          type="text"
          name="object_id"
          placeholder="Filter by Object ID"
          value={filters.object_id}
          onChange={handleFilterChange}
          className="w-full p-2 mb-4 border rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
        <input
          type="text"
          name="title"
          placeholder="Filter by Title"
          value={filters.title}
          onChange={handleFilterChange}
          className="w-full p-2 mb-4 border rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
        />
      </aside>

      {/* Right Content Area */}
      <main className="w-3/4 p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredResults.length > 0 ? (
          filteredResults.map((obj, index) => (
            <Link
              key={index}
              to={`/object/${obj.object_id}`}
              className="block border border-gray-300 rounded p-4 bg-white shadow hover:shadow-lg transition"
            >
              <img
                src={obj.thumbnailUrl || "default-thumbnail.jpg"}
                alt={obj.title || "No Title"}
                className="w-full h-48 object-cover rounded mb-4"
              />
              <div>
                {obj.object_title && (
                  <p className="text-lg font-bold mb-1">{obj.object_title}</p>
                )}
                {obj.description && (
                  <p className="text-gray-600 text-sm mb-1">{obj.description}</p>
                )}
                {obj.object_id && (
                  <p className="text-gray-500 text-xs">
                    <strong>ID:</strong> {obj.object_id}
                  </p>
                )}
                {obj.object_type && (
                  <p className="text-gray-500 text-xs">
                    <strong>Type:</strong> {obj.object_type}
                  </p>
                )}
              </div>
            </Link>
          ))
        ) : (
          <p className="text-gray-500">No results found</p>
        )}
      </main>
    </div>
  );
};

export default Collection;


// ---------------------------------------------
// END: components\Collection.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\CreateData.js
// ---------------------------------------------

import React, { useState } from "react";
import { db, storage } from "../firebase"; // Import Firebase Storage
import { ref as dbRef, set } from "firebase/database";
import { ref as storageRef, uploadBytes, getDownloadURL } from "firebase/storage";
import { useAuth } from "./Auth/AuthContext";
import { Collapse } from "react-collapse";
import { objectTypes } from "./constants";

const CreateData = ({ onCancel }) => {
  const { currentUser } = useAuth();
  const [openSections, setOpenSections] = useState({
    general: true,
    productionDetails: false,
    multimedia: false,
  });

  const [formData, setFormData] = useState({
    object_title: "",
    object_type: "",
    object_id: "",
    title: "",
    description: "",
    createdByEmail: currentUser ? currentUser.email : "",
    creationDate: new Date().toISOString(),
    modifiedDate: new Date().toISOString(),
    object_images: [],
    object_audio: [],
    production_ethnic_group: "",
    culture_period: "",
    producer_name: "",
    school_style: "",
    production_date: "",
    production_place: "",
  });

  const [loading, setLoading] = useState(false);

  const toggleSection = (section) => {
    setOpenSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleFileChange = (e, field) => {
    setFormData({ ...formData, [field]: e.target.files });
  };

  const uploadFiles = async (files, folder) => {
    const urls = [];
    let thumbnailUrl = null;

    for (const file of files) {
      const storagePath = `${folder}/${file.name}`;
      const fileRef = storageRef(storage, storagePath);

      await uploadBytes(fileRef, file);

      const fileURL = await getDownloadURL(fileRef);

      if (!thumbnailUrl) {
        thumbnailUrl = fileURL;
      }

      urls.push(fileURL);
    }

    return { urls, thumbnailUrl };
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (loading) return;

    if (!formData.object_id.trim() || !formData.object_type.trim()) {
      alert("Object ID and Object Type are required.");
      return;
    }

    setLoading(true);

    try {
      const { urls: imagesURLs, thumbnailUrl } = await uploadFiles(formData.object_images, "images");

      const audioURLs = await uploadFiles(formData.object_audio, "audio");

      const updatedFormData = {
        ...formData,
        object_images: imagesURLs,
        object_audio: audioURLs,
        thumbnailUrl: thumbnailUrl || null,
      };

      const recordRef = dbRef(db, `objects/${formData.object_id}`);
      await set(recordRef, updatedFormData);

      alert("Record added successfully!");
      setFormData({
        object_title: "",
        object_type: "",
        object_id: "",
        title: "",
        description: "",
        createdByEmail: currentUser ? currentUser.email : "",
        creationDate: new Date().toISOString(),
        modifiedDate: new Date().toISOString(),
        object_images: [],
        object_audio: [],
        production_ethnic_group: "",
        culture_period: "",
        producer_name: "",
        school_style: "",
        production_date: "",
        production_place: "",
      });

      if (onCancel) onCancel();
    } catch (error) {
      console.error("Error adding record:", error);
      alert("Failed to add record. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="max-w-3xl mx-auto p-6 bg-white shadow-md rounded-md space-y-6">
      <h2 className="text-2xl font-bold">Create New Record</h2>

      <div>
        <button
          type="button"
          onClick={() => toggleSection("general")}
          className="mb-4 bg-gray-200 p-2 rounded hover:bg-gray-300"
        >
          General Information
        </button>
        <Collapse isOpened={openSections.general}>
          <div className="space-y-4">
            <input
              type="text"
              name="object_id"
              placeholder="Object ID (e.g., OBJ-001)"
              value={formData.object_id}
              onChange={handleInputChange}
              required
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="text"
              name="object_title"
              placeholder="Object Title"
              value={formData.object_title}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <select
              name="object_type"
              value={formData.object_type}
              onChange={handleInputChange}
              required
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            >
              <option value="">Select Object Type</option>
              {objectTypes.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
            <input
              type="text"
              name="title"
              placeholder="Title"
              value={formData.title}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <textarea
              name="description"
              placeholder="Description"
              value={formData.description}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
          </div>
        </Collapse>
      </div>

      <div>
        <button
          type="button"
          onClick={() => toggleSection("productionDetails")}
          className="mb-4 bg-gray-200 p-2 rounded hover:bg-gray-300"
        >
          Production Details
        </button>
        <Collapse isOpened={openSections.productionDetails}>
          <div className="space-y-4">
            <input
              type="text"
              name="production_ethnic_group"
              placeholder="Production Ethnic Group"
              value={formData.production_ethnic_group}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="text"
              name="culture_period"
              placeholder="Culture Period"
              value={formData.culture_period}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="text"
              name="producer_name"
              placeholder="Producer Name"
              value={formData.producer_name}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="text"
              name="school_style"
              placeholder="School Style"
              value={formData.school_style}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="text"
              name="production_date"
              placeholder="Production Date"
              value={formData.production_date}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="text"
              name="production_place"
              placeholder="Production Place"
              value={formData.production_place}
              onChange={handleInputChange}
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
          </div>
        </Collapse>
      </div>

      <div>
        <button
          type="button"
          onClick={() => toggleSection("multimedia")}
          className="mb-4 bg-gray-200 p-2 rounded hover:bg-gray-300"
        >
          Multimedia
        </button>
        <Collapse isOpened={openSections.multimedia}>
          <div className="space-y-4">
            <div>
              <label className="block text-gray-700 font-medium mb-1">Upload Images:</label>
              <input
                type="file"
                multiple
                accept="image/*"
                onChange={(e) => handleFileChange(e, "object_images")}
                className="w-full p-2 border border-gray-300 rounded"
              />
            </div>
            <div>
              <label className="block text-gray-700 font-medium mb-1">Upload Audio:</label>
              <input
                type="file"
                multiple
                accept="audio/*"
                onChange={(e) => handleFileChange(e, "object_audio")}
                className="w-full p-2 border border-gray-300 rounded"
              />
            </div>
          </div>
        </Collapse>
      </div>

      <div className="flex justify-between">
        <button
          type="button"
          onClick={onCancel}
          className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={loading}
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          Submit
        </button>
      </div>
    </form>
  );
};

export default CreateData;


// ---------------------------------------------
// END: components\CreateData.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\DeleteData.js
// ---------------------------------------------

import React, { useState } from 'react';
import { ref as storageRef, deleteObject } from "firebase/storage";
import { ref as dbRef, get, remove } from "firebase/database";
import { storage, db } from "../firebase";

function DeleteData({ onDeleteSuccess, onCancel }) {
  const [recordId, setRecordId] = useState("");

  const handleIdChange = (e) => {
    setRecordId(e.target.value);
  };

  const deleteFiles = async (fileURLs) => {
    for (const url of fileURLs) {
      try {
        const fileRef = storageRef(storage, url);
        await deleteObject(fileRef);
      } catch (error) {
        console.error(`Error deleting file: ${url}`, error.message);
      }
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!recordId.trim()) {
      alert("Please enter a valid Record ID.");
      return;
    }

    const recordRef = dbRef(db, `objects/${recordId}`);

    try {
      // Fetch the record to get multimedia file URLs
      const snapshot = await get(recordRef);
      if (!snapshot.exists()) {
        alert("Record not found.");
        return;
      }

      const recordData = snapshot.val();

      // Delete associated files from Firebase Storage
      if (recordData.object_images && recordData.object_images.length > 0) {
        await deleteFiles(recordData.object_images);
      }
      if (recordData.object_audio && recordData.object_audio.length > 0) {
        await deleteFiles(recordData.object_audio);
      }

      // Delete the record from the Realtime Database
      await remove(recordRef);
      alert("Record deleted successfully!");
      setRecordId("");
      if (onDeleteSuccess) onDeleteSuccess(recordId);
    } catch (error) {
      console.error("Error deleting record:", error.message);
      alert("Error deleting record. Please try again.");
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100">
      <div className="w-full max-w-lg bg-white shadow-md rounded-lg p-8">
        <h2 className="text-2xl font-bold text-center mb-6">Delete Record</h2>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="recordId" className="block text-sm font-medium text-gray-700 mb-2">
              Record ID
            </label>
            <input
              type="text"
              id="recordId"
              name="recordId"
              value={recordId}
              onChange={handleIdChange}
              placeholder="Enter Record ID"
              required
              className="w-full p-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-red-400"
            />
          </div>
          <div className="flex justify-between">
            <button
              type="button"
              onClick={onCancel}
              className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
            >
              Delete Record
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default DeleteData;


// ---------------------------------------------
// END: components\DeleteData.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Header.js
// ---------------------------------------------

import React from "react";
import { Link } from "react-router-dom";
import { useAuth } from "./Auth/AuthContext";

const Header = () => {
  const { currentUser } = useAuth();

  return (
    <header className="bg-gray-800 text-white py-4">
      <div className="container mx-auto flex justify-between items-center">
        <h1 className="text-xl font-bold">Catalog App</h1>
        <nav className="flex space-x-4">
          {/* Public Links */}
          <Link to="/" className="hover:underline text-sm">
            Home
          </Link>
          <Link to="/search" className="hover:underline text-sm">
            Search
          </Link>
          <Link to="/collection" className="hover:underline text-sm">
            Collection
          </Link>

          {/* Authenticated Links */}
          {currentUser && (
            <>
              <Link to="/records" className="hover:underline text-sm">
                Manage Records
              </Link>
              <Link to="/logout" className="hover:underline text-sm">
                Logout
              </Link>
            </>
          )}

          {/* Unauthenticated Links */}
          {!currentUser && (
            <>
              <Link to="/login" className="hover:underline text-sm">
                Login
              </Link>
              <Link to="/register" className="hover:underline text-sm">
                Register
              </Link>
            </>
          )}
        </nav>
      </div>
    </header>
  );
};

export default Header;


// ---------------------------------------------
// END: components\Header.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\Home.js
// ---------------------------------------------

import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "./Auth/AuthContext";
import SearchBox from "./SearchBox";

const Home = () => {
  const { isLoggedIn } = useAuth();
  const navigate = useNavigate();

  const handleSearch = (query) => {
    if (query.trim()) {
      navigate(`/results?q=${encodeURIComponent(query)}`); // Redirect to results
    }
  };

  return (
    <div className="text-center py-10 px-5">
      <h1 className="text-4xl font-extrabold mb-5">Welcome to the Catalog</h1>
      <p className="text-lg text-gray-700 mb-8 leading-relaxed max-w-3xl mx-auto">
        Research data on a collection of objects.
      </p>
      {!isLoggedIn ? (
        <div>
          <p className="text-base text-gray-600 mb-5">
            Please login or register to access the features. Use the navigation bar above to proceed.
          </p>
          <div>
            <Link
              to="/login"
              className="mx-4 text-blue-500 hover:underline text-lg"
            >
              Login
            </Link>
            <Link
              to="/register"
              className="mx-4 text-blue-500 hover:underline text-lg"
            >
              Register
            </Link>
          </div>
        </div>
      ) : (
        <SearchBox onSearch={handleSearch} />
      )}
    </div>
  );
};

export default Home;


// ---------------------------------------------
// END: components\Home.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\ObjectDetail.js
// ---------------------------------------------

import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { getDatabase, ref, onValue } from "firebase/database";

const ObjectDetail = () => {
  const { objectId } = useParams(); // Extract objectId from the URL
  const [objectData, setObjectData] = useState(null);

  useEffect(() => {
    const db = getDatabase();
    const objectRef = ref(db, `objects/${objectId}`); // Directly reference object by object_id

    onValue(objectRef, (snapshot) => {
      if (snapshot.exists()) {
        setObjectData(snapshot.val());
      } else {
        console.error("Object not found for ID:", objectId);
        setObjectData(null);
      }
    });
  }, [objectId]);

  if (!objectData) {
    return <p className="text-center text-gray-500">Loading...</p>;
  }

  const filteredFields = Object.entries(objectData || {}).filter(
    ([key, value]) => value && value !== ""
  );

  return (
    <div className="flex flex-col md:flex-row p-6 max-w-6xl mx-auto gap-6">
      {/* Sidebar for Object Details */}
      <aside className="w-full md:w-1/3 bg-gray-100 p-6 rounded-lg shadow">
        <h2 className="mb-6 text-xl font-bold">Object Details</h2>
        {filteredFields.map(([key, value]) => (
          <div key={key} className="mb-4">
            <h3 className="text-sm font-bold capitalize text-gray-700">
              {key.replace(/_/g, " ")}:
            </h3>
            <p className="text-sm text-gray-600 mt-1">{value}</p>
          </div>
        ))}
      </aside>

      {/* Main Content Area */}
      <main className="w-full md:w-2/3 p-6 rounded-lg shadow text-center">
        {objectData.object_images && objectData.object_images.length > 0 ? (
          <img
            src={objectData.object_images[0]}
            alt={objectData.title || "Object Image"}
            className="w-full max-h-96 object-contain mb-6 rounded"
          />
        ) : (
          <p className="text-gray-500">No image available</p>
        )}
        <h2 className="text-2xl font-bold mt-4">
          {objectData.title || "Untitled"}
        </h2>
        <p className="text-gray-600 mt-4">
          {objectData.description || "No description provided."}
        </p>
      </main>
    </div>
  );
};

export default ObjectDetail;


// ---------------------------------------------
// END: components\ObjectDetail.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\ProtectedRoute.js
// ---------------------------------------------

import React from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from './Auth/AuthContext';

const ProtectedRoute = ({ children }) => {
  const { currentUser, emailVerified } = useAuth();
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    setLoading(false); // Assume state stabilizes after mounting
  }, []);

  if (loading) {
    return <div>Loading...</div>; // Add a loading spinner or placeholder
  }

  if (!currentUser) {
    return <Navigate to="/login" />;
  }

  if (!emailVerified) {
    return <Navigate to="/verify-email" />;
  }

  return children;
};

export default ProtectedRoute;


// ---------------------------------------------
// END: components\ProtectedRoute.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\ReadData.js
// ---------------------------------------------

import React, { useEffect, useState } from "react";
import { db } from "../firebase";
import { ref, onValue, query, orderByChild, equalTo, get } from "firebase/database";
import { useAuth } from "./Auth/AuthContext";
import { CSVLink } from "react-csv";

function ReadData({ onSelectRecord, onDelete, onCreate }) {
  const [records, setRecords] = useState([]);
  const [filteredRecords, setFilteredRecords] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const { currentUser, userType } = useAuth();

  useEffect(() => {
    if (!currentUser) return;

    const recordsRef = ref(db, "objects");
    const recordsQuery =
      userType === "admin"
        ? recordsRef
        : query(recordsRef, orderByChild("createdByEmail"), equalTo(currentUser.email));

    const unsubscribe = onValue(recordsQuery, (snapshot) => {
      if (!snapshot.exists()) {
        setRecords([]);
        setFilteredRecords([]);
        return;
      }

      const allRecords = Object.entries(snapshot.val()).map(([object_id, data]) => ({
        object_id,
        ...data,
      }));

      setRecords(allRecords);
      setFilteredRecords(allRecords);
    });

    return () => unsubscribe();
  }, [currentUser, userType]);

  const handleSearch = async () => {
    if (!searchQuery.trim()) {
      setFilteredRecords(records);
      return;
    }

    const objectIdQuery = query(ref(db, "objects"), orderByChild("object_id"), equalTo(searchQuery));

    try {
      const snapshot = await get(objectIdQuery);
      const results = [];
      if (snapshot.exists()) {
        snapshot.forEach((child) => {
          results.push({ object_id: child.key, ...child.val() });
        });
      }

      setFilteredRecords(results);
    } catch (error) {
      console.error("Error fetching search results:", error);
    }
  };

  const headers = records.length > 0
    ? Object.keys(records[0]).map((key) => ({
        label: key.replace(/_/g, " ").toUpperCase(),
        key: key,
      }))
    : [];

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100">
      <div className="w-full max-w-3xl bg-white shadow-md rounded-lg p-8">
        <h3 className="text-2xl font-bold mb-4">Your Records</h3>
        <p className="text-gray-600 mb-4">
          You have <strong>{records.length}</strong> records. Use the buttons below to create, review, update, or delete records.
          You can also export the data as a CSV file.
        </p>

        <div className="mb-4 flex space-x-4">
          <input
            type="text"
            placeholder="Search by object ID"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="p-2 border border-gray-300 rounded w-72 focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
          <button onClick={handleSearch} className="p-2 bg-blue-500 text-white rounded hover:bg-blue-700 focus:ring-2 focus:ring-blue-400">
            Search
          </button>
        </div>

        <div className="mb-4">
          <button onClick={onCreate} className="p-2 bg-green-500 text-white rounded hover:bg-green-700 focus:ring-2 focus:ring-green-400">
            Create New Record
          </button>
        </div>

        <CSVLink
          data={records}
          headers={headers}
          filename="objects_records.csv"
          className="p-2 bg-gray-500 text-white rounded mb-4 inline-block hover:bg-gray-700 focus:ring-2 focus:ring-gray-400"
        >
          Export Records to CSV
        </CSVLink>

        {filteredRecords.length === 0 ? (
          <p className="text-gray-500">No records available</p>
        ) : (
          <ul className="space-y-4">
            {filteredRecords.map((record) => (
              <li
                key={record.object_id}
                className="p-4 border border-gray-300 rounded flex flex-col space-y-2"
              >
                {Object.entries(record).map(([key, value]) => {
                  if (key === "thumbnailUrl") {
                    return (
                      <div key={key} className="flex items-center space-x-2">
                        <strong>{key.replace(/_/g, " ").toUpperCase()}:</strong>
                        <img
                          src={value}
                          alt="Thumbnail"
                          className="w-16 h-16 object-cover rounded-md border border-gray-300"
                        />
                      </div>
                    );
                  }

                  if (key === "object_images" && Array.isArray(value)) {
                    return (
                      <div key={key} className="flex flex-col">
                        <strong>{key.replace(/_/g, " ").toUpperCase()}:</strong>
                        <div className="grid grid-cols-2 gap-2 mt-2">
                          {value.map((imageUrl, index) => (
                            <img
                              key={index}
                              src={imageUrl}
                              alt={`Object ${index + 1}`}
                              className="w-16 h-16 object-cover rounded-md border border-gray-300"
                            />
                          ))}
                        </div>
                      </div>
                    );
                  }

                  return (
                    <p key={key} className="text-sm">
                      <strong>{key.replace(/_/g, " ").toUpperCase()}:</strong> {value?.toString() || "N/A"}
                    </p>
                  );
                })}
                <div className="flex space-x-2 mt-2">
                  <button
                    onClick={() => onSelectRecord(record)}
                    className="p-2 bg-yellow-500 text-white rounded hover:bg-yellow-700 focus:ring-2 focus:ring-yellow-400"
                  >
                    Review Record
                  </button>
                  <button
                    onClick={() => onDelete(record)}
                    className="p-2 bg-red-500 text-white rounded hover:bg-red-700 focus:ring-2 focus:ring-red-400"
                  >
                    Delete Record
                  </button>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}

export default ReadData;


// ---------------------------------------------
// END: components\ReadData.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\RecordManager.js
// ---------------------------------------------

import React, { useState, useEffect } from "react";
import CreateData from "./CreateData";
import ReadData from "./ReadData";
import UpdateData from "./UpdateData";
import DeleteData from "./DeleteData";
import { db } from "../firebase";
import { ref, onValue } from "firebase/database";

const RecordManager = () => {
  const [records, setRecords] = useState([]); // All records
  const [view, setView] = useState("read"); // Current view: "create", "read", "update", "delete"
  const [selectedRecord, setSelectedRecord] = useState(null); // Record selected for update/delete

  useEffect(() => {
    // Fetch records from Firebase
    const recordsRef = ref(db, "objects");
    const unsubscribe = onValue(recordsRef, (snapshot) => {
      if (snapshot.exists()) {
        const fetchedRecords = Object.entries(snapshot.val()).map(([object_id, data]) => ({
          object_id, // Use object_id as the key
          ...data,
        }));
        setRecords(fetchedRecords);
      } else {
        setRecords([]);
      }
    });

    return () => unsubscribe();
  }, []);

  const handleSelectRecord = (record) => {
    setSelectedRecord(record);
    setView("update");
  };

  const handleDelete = (record) => {
    setSelectedRecord(record);
    setView("delete");
  };

  const handleRecordUpdated = () => {
    setSelectedRecord(null);
    setView("read");
  };

  const handleCreate = () => {
    setView("create"); // Switch to Create mode
  };

  const handleCancel = () => {
    setSelectedRecord(null);
    setView("read");
  };

  return (
    <div className="container mx-auto p-4">
      {view === "create" && <CreateData onCancel={handleCancel} />}
      {view === "read" && (
        <ReadData
          records={records}
          onSelectRecord={handleSelectRecord}
          onDelete={handleDelete}
          onCreate={handleCreate}
        />
      )}
      {view === "update" && selectedRecord && (
        <UpdateData selectedRecord={selectedRecord} onRecordUpdated={handleRecordUpdated} onCancel={handleCancel} />
      )}
      {view === "delete" && selectedRecord && (
        <DeleteData selectedRecord={selectedRecord} onDeleteSuccess={handleRecordUpdated} onCancel={handleCancel} />
      )}
    </div>
  );
};

export default RecordManager;


// ---------------------------------------------
// END: components\RecordManager.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\ResultsPage.js
// ---------------------------------------------

import React, { useState, useEffect, useCallback } from "react";
import { getDatabase, ref, onValue } from "firebase/database";
import { Link } from "react-router-dom";
import { objectTypes } from "./constants"; // Import object types for filtering

const ResultsPage = () => {
  const [objects, setObjects] = useState([]); // All fetched objects
  const [filteredResults, setFilteredResults] = useState([]); // Filtered results
  const [filters, setFilters] = useState({
    object_title: "",
    object_type: "",
    object_id: "",
    title: "",
  }); // Filter criteria

  useEffect(() => {
    const db = getDatabase();
    const objectsRef = ref(db, "objects");

    onValue(objectsRef, (snapshot) => {
      const data = snapshot.val();
      const results = Object.entries(data || {}).map(([key, value]) => ({
        object_id: key, // Use object_id as the key
        ...value,
      }));
      setObjects(results);
      setFilteredResults(results); // Initialize filtered results
    });
  }, []);

  const applyFilters = useCallback(() => {
    setFilteredResults(
      objects.filter((obj) => {
        const matchesObjectTitle =
          !filters.object_title ||
          obj.object_title?.toLowerCase().includes(filters.object_title.toLowerCase());
        const matchesObjectType =
          !filters.object_type || obj.object_type === filters.object_type;
        const matchesObjectId =
          !filters.object_id ||
          obj.object_id?.toLowerCase().includes(filters.object_id.toLowerCase());
        const matchesTitle =
          !filters.title ||
          obj.title?.toLowerCase().includes(filters.title.toLowerCase());
        return matchesObjectTitle && matchesObjectType && matchesObjectId && matchesTitle;
      })
    );
  }, [filters, objects]);

  const handleFilterChange = (e) => {
    const { name, value } = e.target;
    setFilters((prevFilters) => ({
      ...prevFilters,
      [name]: value,
    }));
  };

  useEffect(() => {
    applyFilters();
  }, [applyFilters]);

  return (
    <div className="flex flex-col h-screen">
      {/* Top Section for Item Count */}
      <div className="p-4 bg-gray-100 text-left">
        <h2 className="text-lg font-bold">
          Collection search: {filteredResults.length} results
        </h2>
      </div>

      <div className="flex flex-1">
        {/* Left Filter Panel */}
        <aside className="w-1/4 bg-gray-50 p-4 border-r border-gray-300">
          <h2 className="text-xl font-bold mb-4">Filters</h2>
          <input
            type="text"
            name="object_title"
            placeholder="Filter by Object Title"
            value={filters.object_title}
            onChange={handleFilterChange}
            className="w-full p-2 mb-4 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
          <select
            name="object_type"
            value={filters.object_type}
            onChange={handleFilterChange}
            className="w-full p-2 mb-4 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          >
            <option value="">All Object Types</option>
            {objectTypes.map((type) => (
              <option key={type} value={type}>
                {type}
              </option>
            ))}
          </select>
          <input
            type="text"
            name="object_id"
            placeholder="Filter by Object ID"
            value={filters.object_id}
            onChange={handleFilterChange}
            className="w-full p-2 mb-4 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
          <input
            type="text"
            name="title"
            placeholder="Filter by Title"
            value={filters.title}
            onChange={handleFilterChange}
            className="w-full p-2 mb-4 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
        </aside>

        {/* Right Content Area */}
        <main className="w-3/4 p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 overflow-y-auto">
          {filteredResults.length > 0 ? (
            filteredResults.map((obj, index) => (
              <Link
                key={index}
                to={`/object/${obj.object_id}`} // Navigate to ObjectDetail page
                className="border border-gray-300 rounded p-4 bg-white shadow hover:shadow-lg transition"
              >
                <img
                  src={obj.thumbnailUrl || "default-thumbnail.jpg"}
                  alt={obj.title || "No Title"}
                  className="w-full h-48 object-cover rounded mb-4"
                />
                <div>
                  {obj.object_title && (
                    <p className="text-lg font-bold mb-1">{obj.object_title}</p>
                  )}
                  {obj.description && (
                    <p className="text-gray-600 text-sm mb-1">{obj.description}</p>
                  )}
                  {obj.object_id && (
                    <p className="text-gray-500 text-xs">
                      <strong>ID:</strong> {obj.object_id}
                    </p>
                  )}
                </div>
              </Link>
            ))
          ) : (
            <p className="text-gray-500">No results found</p>
          )}
        </main>
      </div>
    </div>
  );
};

export default ResultsPage;


// ---------------------------------------------
// END: components\ResultsPage.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\SearchBox.js
// ---------------------------------------------

import React, { useState } from "react";
import "./SearchBox.css"; // Optional CSS for styling

const SearchBox = ({ onSearch }) => {
  const [query, setQuery] = useState(""); // State to manage search input

  const handleSearch = () => {
    if (query.trim()) {
      onSearch(query); // Call the parent's search handler
    }
  };

  return (
    <div className="search-box" style={{ marginBottom: "20px", textAlign: "center" }}>
      <input
        type="text"
        placeholder="Search by keyword, place, or object ID"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        style={{
          padding: "10px",
          width: "300px",
          marginRight: "10px",
          border: "1px solid #ccc",
          borderRadius: "4px",
        }}
      />
      <button
        onClick={handleSearch}
        style={{
          padding: "10px 20px",
          backgroundColor: "#007BFF",
          color: "white",
          border: "none",
          borderRadius: "4px",
          cursor: "pointer",
        }}
      >
        Search
      </button>
    </div>
  );
};

export default SearchBox;

// ---------------------------------------------
// END: components\SearchBox.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\SearchPage.js
// ---------------------------------------------

import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

const SearchPage = () => {
  const [query, setQuery] = useState("");
  const navigate = useNavigate();

  const handleSearch = (e) => {
    e.preventDefault();
    if (query.trim()) {
      navigate(`/results?q=${encodeURIComponent(query)}`);
    }
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 px-4">
      <h1 className="text-3xl font-bold text-gray-800 mb-6">Search the Catalog</h1>
      <form onSubmit={handleSearch} className="w-full max-w-md">
        <div className="flex items-center border border-gray-300 rounded-lg overflow-hidden shadow-sm">
          <input
            type="text"
            placeholder="Enter search term"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="w-full p-3 text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
          <button
            type="submit"
            className="bg-blue-500 text-white px-4 py-2 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400"
          >
            Search
          </button>
        </div>
      </form>
      <p className="text-sm text-gray-500 mt-4">
        Use the search box above to find objects in the catalog.
      </p>
    </div>
  );
};

export default SearchPage;


// ---------------------------------------------
// END: components\SearchPage.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\UpdateData.js
// ---------------------------------------------

import React, { useState, useEffect } from "react";
import { db, storage } from "../firebase";
import { ref, update } from "firebase/database";
import { ref as storageRef, uploadBytes, getDownloadURL, deleteObject } from "firebase/storage";

function UpdateData({ selectedRecord, onRecordUpdated, onCancel }) {
  const [formData, setFormData] = useState({});
  const [newImages, setNewImages] = useState([]);
  const [newAudio, setNewAudio] = useState([]);
  const [imagesToDelete, setImagesToDelete] = useState([]);

  useEffect(() => {
    if (selectedRecord) {
      setFormData({
        ...selectedRecord,
        object_images: selectedRecord.object_images || [],
        object_audio: selectedRecord.object_audio || [],
        thumbnailUrl: selectedRecord.thumbnailUrl || "",
        modifiedDate: new Date().toISOString(),
        production_ethnic_group: selectedRecord.production_ethnic_group || "",
        culture_period: selectedRecord.culture_period || "",
        producer_name: selectedRecord.producer_name || "",
        school_style: selectedRecord.school_style || "",
        production_date: selectedRecord.production_date || "",
        production_place: selectedRecord.production_place || "",
      });
    }
  }, [selectedRecord]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleFileChange = (e, setFiles) => {
    setFiles(Array.from(e.target.files));
  };

  const handleDeleteImage = (imageUrl) => {
    setImagesToDelete((prev) => [...prev, imageUrl]);
    setFormData((prev) => ({
      ...prev,
      object_images: (prev.object_images || []).filter((url) => url !== imageUrl),
      thumbnailUrl: prev.thumbnailUrl === imageUrl ? null : prev.thumbnailUrl,
    }));
  };

  const uploadFiles = async (files, folder) => {
    const urls = [];
    let thumbnailUrl = null;

    for (const file of files) {
      const storagePath = `${folder}/${file.name}`;
      const fileRef = storageRef(storage, storagePath);
      await uploadBytes(fileRef, file);
      const fileURL = await getDownloadURL(fileRef);

      if (!thumbnailUrl) {
        thumbnailUrl = fileURL;
      }

      urls.push(fileURL);
    }

    return { urls, thumbnailUrl };
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.object_id) {
      alert("Invalid record ID.");
      return;
    }

    const recordRef = ref(db, `objects/${formData.object_id}`);
    const updatedRecord = { ...formData, modifiedDate: new Date().toISOString() };

    try {
      for (const imageUrl of imagesToDelete) {
        const imageRef = storageRef(storage, imageUrl);
        await deleteObject(imageRef);
      }

      if (newImages.length > 0) {
        const { urls: imageUrls, thumbnailUrl } = await uploadFiles(newImages, "images");
        updatedRecord.object_images = [...(formData.object_images || []), ...imageUrls];
        updatedRecord.thumbnailUrl = thumbnailUrl || updatedRecord.thumbnailUrl;
      }

      if (newAudio.length > 0) {
        const audioUrls = await uploadFiles(newAudio, "audio");
        updatedRecord.object_audio = [...(formData.object_audio || []), ...audioUrls];
      }

      await update(recordRef, updatedRecord);
      alert("Record updated successfully!");
      if (onRecordUpdated) onRecordUpdated(updatedRecord);
    } catch (error) {
      console.error("Error updating record:", error.message);
      alert("Failed to update record. Please try again.");
    }
  };

  const renderInputFields = () => (
    <>
      {Object.entries(formData).map(([key, value]) => {
        if (key === "object_images") {
          return (
            <div key={key} className="mb-4">
              <label className="block text-sm font-medium text-gray-700">Existing Images</label>
              <div className="grid grid-cols-2 gap-4 mt-2">
                {Array.isArray(value) &&
                  value.map((imageUrl, index) => (
                    <div key={index} className="relative">
                      <img
                        src={imageUrl}
                        alt={`Object ${index + 1}`}
                        className="w-full h-auto rounded-lg shadow border"
                      />
                      <button
                        type="button"
                        onClick={() => handleDeleteImage(imageUrl)}
                        className="absolute top-1 right-1 bg-red-500 text-white text-xs px-2 py-1 rounded"
                      >
                        Remove
                      </button>
                    </div>
                  ))}
              </div>
              <label className="block text-sm font-medium text-gray-700 mt-4">Add New Images</label>
              <input
                type="file"
                multiple
                accept="image/*"
                onChange={(e) => handleFileChange(e, setNewImages)}
                className="block w-full mt-1 p-2 border border-gray-300 rounded"
              />
            </div>
          );
        }

        if (key === "object_audio") {
          return (
            <div key={key} className="mb-4">
              <label className="block text-sm font-medium text-gray-700">Add New Audio</label>
              <input
                type="file"
                multiple
                accept="audio/*"
                onChange={(e) => handleFileChange(e, setNewAudio)}
                className="block w-full mt-1 p-2 border border-gray-300 rounded"
              />
            </div>
          );
        }

        if (key === "thumbnailUrl") {
          return (
            <div key={key} className="mb-4">
              <label className="block text-sm font-medium text-gray-700">Thumbnail</label>
              {value ? (
                <img
                  src={value}
                  alt="Thumbnail"
                  className="w-24 h-24 object-cover rounded-md border border-gray-300 mt-2"
                />
              ) : (
                <div className="w-24 h-24 bg-gray-200 flex items-center justify-center rounded-md mt-2">
                  No Thumbnail
                </div>
              )}
            </div>
          );
        }

        return (
          <div key={key} className="mb-4">
            <label className="block text-sm font-medium text-gray-700">{key.replace(/_/g, " ").toUpperCase()}</label>
            <input
              type="text"
              name={key}
              value={value || ""}
              onChange={handleChange}
              className="block w-full mt-1 p-2 border border-gray-300 rounded"
            />
          </div>
        );
      })}
    </>
  );

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100">
      <div className="w-full max-w-lg bg-white shadow-md rounded-lg p-8">
        <h2 className="text-2xl font-bold text-center mb-6">Update Record</h2>
        <form onSubmit={handleSubmit} className="space-y-6">
          {renderInputFields()}
          <div className="flex justify-between mt-4">
            <button
              type="button"
              onClick={onCancel}
              className="w-1/2 bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-md mr-2"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="w-1/2 bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-md"
            >
              Update Record
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default UpdateData;


// ---------------------------------------------
// END: components\UpdateData.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\constants.js
// ---------------------------------------------

// src/components/constants.js
export const objectTypes = [
    "Figure",
    "Coin",
    "Ivory",
    "Jewellery",
    "Sculpture",
    "Pottery",
    "Postcard",
    "Painting",
    "Ceramic",
    "Fabric",
    "Other", // Add more as needed
  ];
  

// ---------------------------------------------
// END: components\constants.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: components\exportRecordsToCSV.js
// ---------------------------------------------

import { ref, get } from "firebase/database";
import { db } from "../firebase";
import { useAuth } from "./Auth/AuthContext"; // Use AuthContext for authentication and verification
import "./exportRecordsToCSV.css";

function exportRecordsToCSV() {
  const { currentUser, emailVerified } = useAuth(); // Access current user and email verification status

  // Check user authentication and email verification
  if (!currentUser) {
    alert("You must be logged in to export records.");
    return;
  }

  if (!emailVerified) {
    alert("You must verify your email before exporting records.");
    return;
  }

  // Reference to the "objects" node
  const recordsRef = ref(db, `objects`);

  get(recordsRef)
    .then((snapshot) => {
      if (snapshot.exists()) {
        const records = snapshot.val();
        const recordsArray = Object.entries(records).map(([object_id, data]) => {
          const { object_images = [], object_audio = [], ...rest } = data;
          return {
            object_id, // Use object_id as the key
            ...rest,
            object_images: object_images.join("; "), // Combine image URLs into a single string
            object_audio: object_audio.join("; "), // Combine audio URLs into a single string
          };
        });
        const csvContent = convertToCSV(recordsArray);
        downloadCSV(csvContent, "object_records.csv");
      } else {
        alert("No records available to export.");
      }
    })
    .catch((error) => {
      console.error("Error fetching records:", error.message);
      alert("Failed to fetch records. Please try again.");
    });
}

// Convert JSON data to CSV format
function convertToCSV(data) {
  if (!data.length) return "";

  // Dynamically fetch all headers from the first record
  const headers = Object.keys(data[0]).join(",");

  // Map each record to a CSV row
  const rows = data.map((record) =>
    Object.values(record)
      .map((value) => {
        // Convert arrays to strings and escape quotes
        if (Array.isArray(value)) {
          return `"${value.join("; ").replace(/"/g, '""')}"`;
        }
        return `"${String(value).replace(/"/g, '""')}"`; // Escape quotes in values
      })
      .join(",")
  );

  return [headers, ...rows].join("\n");
}

// Download the generated CSV file
function downloadCSV(csvContent, fileName) {
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", fileName);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export default exportRecordsToCSV;

/* exportRecordsToCSV.css */
.download-button {
  background-color: #007bff;
  color: white;
  font-weight: bold;
  padding: 10px 20px;
  border-radius: 5px;
  border: none;
  cursor: pointer;
}

.download-button:hover {
  background-color: #0056b3;
}


// ---------------------------------------------
// END: components\exportRecordsToCSV.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: firebase.js
// ---------------------------------------------

import { initializeApp } from "firebase/app";
import {
  getDatabase,
  ref,
  query,
  orderByKey,
  get,
  limitToFirst,
} from "firebase/database"; // Import query functions
import { getAnalytics } from "firebase/analytics"; // Optional, for analytics
import {
  getAuth,
  setPersistence,
  browserSessionPersistence,
} from "firebase/auth"; // For authentication
import {
  getStorage,
  ref as storageRef,
  uploadBytes,
  getDownloadURL,
} from "firebase/storage"; // For Storage
import { enableLogging } from "firebase/database";

// Firebase configuration
const firebaseConfig = {
  apiKey: process.env.REACT_APP_API_KEY,
  authDomain: process.env.REACT_APP_AUTHDOMAIN,
  databaseURL: process.env.REACT_APP_DATABASEURL,
  projectId: process.env.REACT_APP_PROJECTID,
  storageBucket: process.env.REACT_APP_STORAGEBUCKET,
  messagingSenderId: process.env.REACT_APP_MESSAGINGSENDERID,
  appId: process.env.REACT_APP_APPID,
  measurementId: process.env.REACT_APP_MEASUREMENTID,
};

// Initialize Firebase App
const app = initializeApp(firebaseConfig);

// Realtime Database instance
export const db = getDatabase(app); // For Realtime Database

// Firebase Storage instance
export const storage = getStorage(app); // For File Storage

// Optional: Initialize Firebase Analytics
if (firebaseConfig.measurementId) {
  getAnalytics(app);
}

// Authentication instance
export const auth = getAuth(app);

// Set session persistence
setPersistence(auth, browserSessionPersistence)
  .then(() => {
    console.log("Session persistence set to browser session only");
  })
  .catch((error) => {
    console.error("Error setting session persistence:", error);
  });

// Fetch all objects data
export const fetchAllObjects = async () => {
  try {
    const objectsRef = ref(db, "objects");
    const snapshot = await get(objectsRef); // Fetch all data at the "objects" node
    if (snapshot.exists()) {
      return snapshot.val(); // Return all objects
    } else {
      console.warn("No objects data found");
      return {};
    }
  } catch (error) {
    console.error("Error fetching objects data:", error.message);
    throw error;
  }
};

// Example: Fetch limited objects data
export const fetchLimitedObjects = async (limit = 10) => {
  try {
    const objectsRef = ref(db, "objects");
    const limitedQuery = query(objectsRef, orderByKey(), limitToFirst(limit));
    const snapshot = await get(limitedQuery);
    return snapshot.val() || {};
  } catch (error) {
    console.error("Error fetching limited objects data:", error.message);
    throw error;
  }
};

// Example: Fetch object by key
export const fetchObjectByKey = async (key) => {
  try {
    const objectRef = ref(db, `objects/${key}`);
    const snapshot = await get(objectRef);
    return snapshot.val() || null;
  } catch (error) {
    console.error("Error fetching object by key:", error.message);
    throw error;
  }
};

// Upload file to Firebase Storage
export const uploadFile = async (file, folder = "uploads") => {
  try {
    const fileRef = storageRef(storage, `${folder}/${file.name}`);
    await uploadBytes(fileRef, file);
    const downloadURL = await getDownloadURL(fileRef);
    console.log(`File uploaded successfully: ${downloadURL}`);
    return downloadURL;
  } catch (error) {
    console.error("Error uploading file:", error.message);
    throw error;
  }
};

// Fetch file download URL from Firebase Storage
export const fetchFileURL = async (path) => {
  try {
    const fileRef = storageRef(storage, path);
    const downloadURL = await getDownloadURL(fileRef);
    console.log(`File URL fetched: ${downloadURL}`);
    return downloadURL;
  } catch (error) {
    console.error("Error fetching file URL:", error.message);
    throw error;
  }
};

// Enable logging for Firebase
enableLogging(true);


// ---------------------------------------------
// END: firebase.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: index.js
// ---------------------------------------------

import React from "react";
import ReactDOM from "react-dom/client"; // Use createRoot API for React 18+
import { BrowserRouter } from "react-router-dom";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
import { AuthProvider } from "./components/Auth/AuthContext"; // Import AuthProvider

// Create root and render the application
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <AuthProvider>
      <BrowserRouter
        future={{
          v7_startTransition: true, // Opt into React startTransition behavior for state updates
          v7_relativeSplatPath: true, // Enable new relative route resolution within Splat routes
        }}
      >
        <App />
      </BrowserRouter>
    </AuthProvider>
  </React.StrictMode>
);

// Optional: Log performance metrics
reportWebVitals();


// ---------------------------------------------
// END: index.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: reportWebVitals.js
// ---------------------------------------------

const reportWebVitals = onPerfEntry => {
  if (onPerfEntry && onPerfEntry instanceof Function) {
    import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
      getCLS(onPerfEntry);
      getFID(onPerfEntry);
      getFCP(onPerfEntry);
      getLCP(onPerfEntry);
      getTTFB(onPerfEntry);
    });
  }
};

export default reportWebVitals;


// ---------------------------------------------
// END: reportWebVitals.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: setupTests.js
// ---------------------------------------------

// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';


// ---------------------------------------------
// END: setupTests.js
// ---------------------------------------------


// ---------------------------------------------
// BEGIN: utils\fetchData.js
// ---------------------------------------------

// src/utils/fetchData.js
import { ref, get } from "firebase/database";
import { db } from "../firebase";

export const fetchData = async () => {
  const dbRef = ref(db, "objects");

  try {
    // Fetch all records from the "objects" node
    const snapshot = await get(dbRef);
    if (snapshot.exists()) {
      return Object.values(snapshot.val()); // Convert the snapshot to an array of objects
    } else {
      return []; // Return an empty array if no data exists
    }
  } catch (error) {
    console.error("Error fetching data:", error);
    throw error;
  }
};


// ---------------------------------------------
// END: utils\fetchData.js
// ---------------------------------------------

// =============================================
// End of merged file
// =============================================
